sylius_twig_hooks:
    hooks:
        'sylius_admin.base#javascripts':
            monsieurbiz_sylius_richeditor_javascripts:
                template: '@MonsieurBizSyliusRichEditorPlugin/Admin/app.html.twig'

        'sylius_shop.base#javascripts':
            monsieurbiz_sylius_richeditor_javascripts:
                template: '@MonsieurBizSyliusRichEditorPlugin/Shop/app.html.twig'
